name: Build PocketMine-MP Phar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Download binaries
      run: |
        wget https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/lastSuccessfulBuild/artifact/PHP-7.3-Linux-x86_64.tar.gz
        tar -xf PHP-7.3-Linux-x86_64.tar.gz
    - name: Run composer
      run: |
        composer install
